FROM phpmyadmin/phpmyadmin

# Increase PHP upload limits
RUN echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/upload-limits.ini && \
    echo "post_max_size = 512M" >> /usr/local/etc/php/conf.d/upload-limits.ini && \
    echo "upload_max_filesize = 512M" >> /usr/local/etc/php/conf.d/upload-limits.ini
